name: run scripts/feed.py

on:
  schedule:
   - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          
       # Setup Python, pipenv and pipfile packages
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: 3.9
          
#       - name: Run pipenv shell
#         run: pipenv shell

      - name: pip install feedparser
        run: pip install feedparser

      - name: execute py script # run main.py
        run: python scripts/feed.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated daily feed" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
